---
#- name: Install PHP74 from REMI repository
 # ansible.builtin.package:
 #   name: "{{ remi_php74_packages }}"
 #   state: present

- name: Install php packages
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
    enablerepo: "{{ php_repo }}"
  tags:
    - install_packages

- name: Enable and start php-fpm service
  service:
    name: php74-php-fpm
    state: started
    enabled: true
  when:
    - remi_php74_fpm_enable|bool
    - remi_php74_fpm_pools is defined