---
- name: Install php-fpm
  dnf:
    name: php:remi-7.4
    state: present

- name: Install php packages
  dnf:
    name: "{{php_packages}}"
    state: present
    #enablerepo: "{{php_repo}}"
  tags:
    - install_packages

- name: start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
