---
- name: reload nginx service
  service:
    name: nginx
    state: reloaded
    enabled: yes
  listen: "reload nginx service"

- name: restart nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes
  listen: "restart nginx service"