---
- name: Enable EPEL Repository 
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '9'

- rpm_key:
      state: present
      key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2021"

- name: Download epel GPG key
  rpm_key:
      state: present
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"

- name: Enable REMI Repository 
  dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
    state: present
  #when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '9'

- name: DNF update the system
  dnf:
      name:  "*"
      state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts  ['distribution_major_version'] >= '9'

#- name: Add Remi
 # dnf:
  #    name: {{php_module_stream}}
  #    state: present